server:
  port: 8761
  # port: 8762
encrypt:
  key: hsj
spring:
  application:
    name: hsj-common-eureka-server
  profiles:
    active: dev,master
    # active: dev,slave
eureka:
  instance:
    prefer-ip-address: true