server:
  port: 8888
encrypt:
  key: hsj
spring:
  application:
    name: hsj-common-config-server
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/hsjconfig
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka